#include <iostream>
using namespace std;
void test(int x)
{
    try       /* try block*/
    {
        if (x == 0)
            throw x;
        if (x == -1)
            throw 'x';
        if (x == 1)
            throw 1.0;
    }
    catch (...)                 /* catch block*/
    {
        cout << "caught an exception \n";
    }
}
int main()           /* main function*/
{
    cout << "testing generic catch \n";
    test(-1);
    test(0);
    test(1);
    return 0;
}
